### PR TITLE
Changes for Crucible Hook and Source Editor

### PR DESCRIPTION
**Pull request by hasithad**
- Resurrected the about page
- Removed the plugin icons from hero-logo since there are more than three.
- Added Source Editor for Confluence to products list (missing logo).
- Added Crucible Review Hook to products list (missing logo).
- Added Markdown Render Macro to products list (missing logo).
- Added Autowatch for JIRA to products list (missing logo).
- Fixed up .less scripts to refer to all products by their name.
- Removed the demo link from the navbar. Better with products.

### CODE REVIEW

**Comment by hasithad** [comment]
Markdown Render Macro and Autowatch are ready to go but need images. Commits just have them commented out.

**Comment by mdavoodi** [comment]
Things I've noticed that need to be fixed:
- The Docs link for Crucible leads to the wrong documentation.
- If you pay close attention you'll notice the Editor, Search, and Code Nav all have icons that have a slight shadow. You missed that on the new icons.
- Kill the about page. The page content isn't to my liking yet and it's still negative energy to put any time into it.
- You missed the product sites link for the new products at the bottom header of the page.
- The little arrows for the product icons are now black. They used to be the same color as the background they were on. You can look at mohamicorp.com to compare. Example:

image
- The Crucible Review Hook screenshot is being stretched out on the product bar. Compare it to the search icon, that's what it should look like. You should be able to use the search icon css as a basis.
  image

**Comment by hasithad** [comment]
Crucible link appears correct to me (matches marketplace, at least). 
Modified the other stuff. I personally like the black caret because it draws attention to the button, but I'll defer on that one.

**Comment by mdavoodi** [comment]
Looks good, last broken thing I see is the Search icon is now stretched out on it's page:

image

Compare to prod to see the difference.

**Comment by mdavoodi** [comment]
Changes are live now.

**Pull request merged**
